### ISSUE TITLE
Fix About Description text to take up more room on page

### ISSUE THREAD

**Issue by MrGDS2** [MrGDS2/Madgiraffestudios.com#43]

**Comment by estherkoko** [comment]
@MrGDS2 not sure why this is assigned to me but I see you have your PR linked to it

**Comment by MrGDS2** [comment]
You told me you'd fix it

**Comment by estherkoko** [comment]
> You told me you'd fix it

Oh, okay. It's been addressed on this issue #35  "Reduce font size of different services on responsive" which is part of this PR Tmp/128/removereactlogo
